BEGIN;

CREATE TYPE process AS ENUM (
  'Washed/Wet',
  'Honey',
  'Pulped Natural',
  'Natural/Dry',
  'Lactic',
  'Other/Blend'
);

CREATE TABLE coffee_review (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  display_name TEXT NOT NULL,
  roaster_name TEXT NOT NULL,
  coffee_name TEXT NOT NULL,
  coffee_origin TEXT,
  process_method process NOT NULL,
  posted_on TIMESTAMPTZ DEFAULT now(),
  body TEXT,
  active BOOLEAN DEFAULT TRUE
);

COMMIT;